-- 1 .High Spenders: List all unique Customer Names who have spent more than $500 in a single transaction.
SELECT DISTINCT `Customer Name` FROM ecommerce_customer_data_custom_ratios
WHERE `Total Purchase Amount` > 500;

-- 2. Category Check: Show all purchases made in the 'Electronics' or 'Home' categories.
SELECT * FROM ecommerce_customer_data_custom_ratios
WHERE `Product Category` IN('Electronics', 'Home');

-- 3. Revenue Check: What is the Total Revenue (sum of Total Purchase Amount) generated by the entire store?
SELECT SUM(`Total Purchase Amount`) FROM ecommerce_customer_data_custom_ratios;

-- 4. Average Ticket: What is the Average Price of a product sold in the 'Clothing' category?
SELECT AVG(`Product Price`) FROM ecommerce_customer_data_custom_ratios
WHERE `Product Category` = 'Clothing';

-- 5. Popularity Contest: Which Product Category has the highest number of total items sold (sum of Quantity)?
SELECT `Product Category`, SUM(`Quantity`) FROM ecommerce_customer_data_custom_ratios
GROUP BY `Product Category`
ORDER BY SUM(`Quantity`) DESC
LIMIT 1;

-- 6. Gender Split: Calculate the Total Purchase Amount broken down by Gender.
SELECT SUM(`Total Purchase Amount`), Gender FROM ecommerce_customer_data_custom_ratios
GROUP BY Gender;

-- 7. The "Big Spender" Portfolio Piece: List the Top 5 customers who have spent the most money in total across all their purchases.
SELECT `Customer Name`, SUM(`Total Purchase Amount`) FROM ecommerce_customer_data_custom_ratios
GROUP BY `Customer Name`
ORDER BY SUM(`Total Purchase Amount`) DESC
LIMIT 5;

-- BONUS TASK: Show all columns for the 10 most recent purchases made in the store.
SELECT * FROM ecommerce_customer_data_custom_ratios
ORDER BY CAST(`Purchase Date` AS DATETIME) DESC
LIMIT 10;
